# This file was generated by https://github.com/MagnusOpera/FeatStudio/blob/main/.github/scripts/generate-homebrew-cask
cask "featstudio" do
  arch arm: "arm64", intel: "x64"

  version "0.0.2"
  sha256 arm: "d0bb7f312ac42e7970ea4f42e5d8e1af667819a9e86b5aa18c6f9e5b98f859d4", intel: "1ae4db463176be706137e4e33db9c07297bb5516af4a3722c9f8b5787c40d65d"

  if Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.0.2/FeatStudio-0.0.2-mac-arm64.zip"
  else
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.0.2/FeatStudio-0.0.2-mac-x64.zip"
  end

  name "FeatStudio"
  desc "Desktop workspace for planning and building software with Codex"
  homepage "https://github.com/MagnusOpera/FeatStudio"

  app "FeatStudio.app"
end
