# This file was generated by https://github.com/MagnusOpera/FeatStudio/blob/main/.github/scripts/generate-homebrew-cask
cask "featstudio" do
  arch arm: "arm64", intel: "x64"

  version "0.0.4"
  sha256 arm: "490b19efb6fb7c59f79597b2d7aeb3f6c03d06c4eee48eeb9fdbeb587d1b952d", intel: "bdd0a14934313f27d014d2775dfeaba1351f89312a602753e53db888b7acc32a"

  if Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.0.4/FeatStudio-0.0.4-mac-arm64.zip"
  else
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.0.4/FeatStudio-0.0.4-mac-x64.zip"
  end

  name "FeatStudio"
  desc "Desktop workspace for planning and building software with Codex"
  homepage "https://github.com/MagnusOpera/FeatStudio"

  app "FeatStudio.app"
end
