# This file was generated by https://github.com/MagnusOpera/FeatStudio/blob/main/.github/scripts/generate-homebrew-cask
cask "featstudio" do
  arch arm: "arm64", intel: "x64"

  version "0.1.0"
  sha256 arm: "08af8d909ce13f1d065eb92bfb8444f629751791e0e3d9058d6585ee35d03b6f", intel: "55121fb9643abd4eebef27eb9c787990727fcfd711cf6183bbe229a3d9212590"

  if Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.1.0/FeatStudio-0.1.0-mac-arm64.zip"
  else
    url "https://github.com/MagnusOpera/FeatStudio/releases/download/v0.1.0/FeatStudio-0.1.0-mac-x64.zip"
  end

  name "FeatStudio"
  desc "Desktop workspace for planning and building software with Codex"
  homepage "https://github.com/MagnusOpera/FeatStudio"

  app "FeatStudio.app"
end
