# This file was generated by https://github.com/MagnusOpera/forge/blob/main/.github/scripts/generate-homebrew-cask
cask "forge" do
  version "0.0.7"
  sha256 "de0e06130ceb9c8d51ca91cbcb18f5d0d154c95fcd43bbde7297a62c3d895544"

  url "https://github.com/MagnusOpera/forge/releases/download/0.0.7/forge-0.0.7-mac-arm64.zip"
  name "Forge"
  desc "Focus-first desktop GitHub client"
  homepage "https://github.com/MagnusOpera/forge"

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Forge.app"
end
