# This file was generated by https://github.com/MagnusOpera/forge/blob/main/.github/scripts/generate-homebrew-cask
cask "forge" do
  version "0.0.5"
  sha256 "5d29f6ecfa13f594a6e9c7f11d58cf645240f22f8fddcc846bbdf7f96ea9711f"

  url "https://github.com/MagnusOpera/forge/releases/download/0.0.5/forge-0.0.5-mac-arm64.zip"
  name "Forge"
  desc "Focus-first desktop GitHub client"
  homepage "https://github.com/MagnusOpera/forge"

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Forge.app"
end
