# This file was generated by https://github.com/MagnusOpera/forge/blob/main/.github/scripts/generate-homebrew-cask
cask "forge" do
  version "0.0.16"
  sha256 "3306d3c854d77d20a50afc0c61c16e7aa709e49e226a32bdb6f0c10af7db178c"

  url "https://github.com/MagnusOpera/forge/releases/download/0.0.16/forge-0.0.16-mac-arm64.zip"
  name "Forge"
  desc "Focus-first desktop GitHub client"
  homepage "https://github.com/MagnusOpera/forge"

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Forge.app"
end
