# Generated by the Starpac release workflow.
class D1pac < Formula
  desc "Desired-state schema packaging CLI for Cloudflare D1"
  homepage "https://github.com/MagnusOpera/starpac"
  version "0.6.1"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/starpac/releases/download/v0.6.1/d1pac-0.6.1-darwin-arm64.zip"
    sha256 "92d052cb329de1485a779f136de0a6504b56a6c016607b4827733d668c013744"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/starpac/releases/download/v0.6.1/d1pac-0.6.1-linux-arm64.zip"
    sha256 "e3f507f64b1597f453b153d2bc242a9b232037a75631f972d0f170095118d077"
  end

  if OS.linux? && Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/starpac/releases/download/v0.6.1/d1pac-0.6.1-linux-x64.zip"
    sha256 "b280a434dceb1053ae9cc390f7bcd00dba712d9f59716a81302ffd15a7e830cd"
  end

  def install
    bin.install "d1pac"
  end

  test do
    system bin/"d1pac", "--version"
  end
end
