# This file was generated by https://github.com/magnusopera/fscript/blob/main/.github/scripts/generate-homebrew-tap
class Fscript < Formula
  desc "Embeddable F#/ML-style scripting language and CLI"
  homepage "https://github.com/magnusopera/fscript"
  version "0.39.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.39.0/fscript-0.39.0-darwin-x64.zip"
    sha256 "9952c8b9fa594e5855c81c864bbe368b08f97e200b5fe55c93806c436afcb509"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.39.0/fscript-0.39.0-darwin-arm64.zip"
    sha256 "9b4c5f7a45718b943c12e8e28d73447a318b6a2c64c791141f84616eb1440eb4"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.39.0/fscript-0.39.0-linux-x64.zip"
    sha256 "ae7b8c3c93be2fa9fc591f958c62473efeb012600c3543fffb82b36057e5fd3f"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.39.0/fscript-0.39.0-linux-arm64.zip"
    sha256 "603055a6ec8a3601efb806ff5594a2860181c30de516b81ccbdf2ba846d651ac"
  end

  def install
    bin.install "fscript" => name
  end

  test do
    system bin/name, "--help"
  end
end
