# This file was generated by https://github.com/magnusopera/fscript/blob/main/.github/scripts/generate-homebrew-tap
class Fscript < Formula
  desc "Embeddable F#/ML-style scripting language and CLI"
  homepage "https://github.com/magnusopera/fscript"
  version "0.52.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.52.0/fscript-0.52.0-darwin-x64.zip"
    sha256 "928b6d5290c0c1db09e13d8040f75cbf2e1442b63980059d150d82d9e19b02d8"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.52.0/fscript-0.52.0-darwin-arm64.zip"
    sha256 "f066fb939f05c78f381986e1b0e40e4c58b147e0dbcade2ec945d4f3afe52d88"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.52.0/fscript-0.52.0-linux-x64.zip"
    sha256 "6d30f125ac3d671c5151b5af5ced2ef534638ed992f6ad84149b43553a5c860a"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.52.0/fscript-0.52.0-linux-arm64.zip"
    sha256 "4f7665e27e7ac405482e0faa9679054d2500448a7718b3427ffb762ac832769d"
  end

  def install
    bin.install "fscript" => name
  end

  test do
    system bin/name, "--help"
  end
end
