# This file was generated by https://github.com/magnusopera/fscript/blob/main/.github/scripts/generate-homebrew-tap
class FscriptNext < Formula
  desc "Embeddable F#/ML-style scripting language and CLI"
  homepage "https://github.com/magnusopera/fscript"
  version "0.1.3-next"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.1.3-next/fscript-0.1.3-next-darwin-x64.zip"
    sha256 "608df0d70c5987ea2b68b479d11c66b31abbdc093fbb5327c014c0f412de660e"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.1.3-next/fscript-0.1.3-next-darwin-arm64.zip"
    sha256 "4b47469d5474a7f277563d66844da73ec4dc8abdc810cb23485b323044c514c3"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.1.3-next/fscript-0.1.3-next-linux-x64.zip"
    sha256 "07c6d8b2135001352a6218015826736d67fe3a94882d6d06d06a3ed4d67a570e"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/FScript/releases/download/0.1.3-next/fscript-0.1.3-next-linux-arm64.zip"
    sha256 "5b51d9781c785733f954a6a9d82006340c7925d8a4ff4cd51ca2b1e05fba17e9"
  end

  def install
    bin.install "fscript" => name
  end

  test do
    system bin/name, "--help"
  end
end
