# This file was generated by https://github.com/MagnusOpera/pgpac/blob/main/.github/scripts/generate-homebrew-tap
class Pgpac < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/pgpac"
  version "0.5.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.5.0/pgpac-0.5.0-darwin-arm64.zip"
    sha256 "510c9ba2cafbcca58eed78ace0bdec93b8b83746d1d1cae957562ca86905dd8a"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.5.0/pgpac-0.5.0-linux-arm64.zip"
    sha256 "e5fdde81ec45b38227d58a7174537c534ae5781c7317c79be3708ea9d2e9c98e"
  end

  if OS.linux? && Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.5.0/pgpac-0.5.0-linux-x64.zip"
    sha256 "9ad2426f990e86f9ea9cfd02220cc5b55ec6215943edced6ef667380d1a22dad"
  end

  def install
    bin.install "pgpac"
  end

  test do
    system bin/"pgpac", "--version"
  end
end
