# This file was generated by https://github.com/MagnusOpera/pgpac/blob/main/.github/scripts/generate-homebrew-tap
class Pgpac < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/pgpac"
  version "0.3.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.3.0/pgpac-0.3.0-darwin-arm64.zip"
    sha256 "f9f94e2ffe112621fee573bdadc56cd9d6fcdd86421dbae063b3182d46b84e2a"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.3.0/pgpac-0.3.0-linux-arm64.zip"
    sha256 "89b7abc40454be0b1c0114694c9c77d08723332efd2d8c3e5a0097d2d0d172a5"
  end

  if OS.linux? && Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/pgpac/releases/download/0.3.0/pgpac-0.3.0-linux-x64.zip"
    sha256 "f50167de2629db3ae5ae87c76168703b2b21b1da4b2a52cfc0b295f06ffadce3"
  end

  def install
    bin.install "pgpac"
  end

  test do
    system bin/"pgpac", "--version"
  end
end
