# This file was generated by https://github.com/MagnusOpera/pgpackage/blob/main/.github/scripts/generate-homebrew-tap
class Pgpackage < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/pgpackage"
  version "0.0.2"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/MagnusOpera/pgpackage/releases/download/0.0.2/pgpackage-0.0.2-darwin-arm64.zip"
    sha256 "98c7e1ee8005149e3338a5221e8abf555430b677b8edb2f4fc15240c4c41c594"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/MagnusOpera/pgpackage/releases/download/0.0.2/pgpackage-0.0.2-linux-arm64.zip"
    sha256 "10ff72dad3d913c3ee24225b244a4c6f00270a985a45452b0ca0825ee79d31d4"
  end

  def install
    bin.install "pgpackage"
  end

  test do
    system bin/"pgpackage", "--version"
  end
end
