# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-tap
class Terrabuild < Formula
  desc "Seamless CI/CD tool for building and deploying monorepos."
  homepage "https://terrabuild.io"
  version "0.152.2"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.152.2/terrabuild-0.152.2-darwin-x64.zip"
    sha256 "ca592b0e4b55366e17fa9b0406c0f87b5085d27f2e6e0b521740a2fab61b9f6b"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.152.2/terrabuild-0.152.2-darwin-arm64.zip"
    sha256 "1a7a67bd042100114037cf00dfca74bdf5d1c12f04aacaeb26d77469a7992460"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.152.2/terrabuild-0.152.2-linux-x64.zip"
    sha256 "32973e29c5605a21011fd9b71d00860c4caa8b25d00c91c92be4dd0e9b91a5ec"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.152.2/terrabuild-0.152.2-linux-arm64.zip"
    sha256 "44d35e374c806cff716800768e59eeb3748adca931ae2852c316463c71b26f47"
  end

  conflicts_with "terrabuild"
  conflicts_with "terrabuild-next"

  def install
    bin.install "terrabuild"
  end

  test do
    system "#{bin}/terrabuild version"
  end
end
