# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-tap
class Terrabuild < Formula
  desc "Seamless CI/CD tool for building and deploying monorepos."
  homepage "https://terrabuild.io"
  version "0.179.0"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.179.0/terrabuild-0.179.0-darwin-x64.zip"
    sha256 "1cd8fecb83cc98fb10c79810cd83b74731d3582efac4df6631a1259ffc2ae551"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.179.0/terrabuild-0.179.0-darwin-arm64.zip"
    sha256 "4da957cb9d08a7d42749b989a78388fbc7194483aac3f58055ff2793a5c2a3c2"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.179.0/terrabuild-0.179.0-linux-x64.zip"
    sha256 "3833f4bf6346fd921255fd3f5ab563e9e77132e05821632325f798a01140dadf"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.179.0/terrabuild-0.179.0-linux-arm64.zip"
    sha256 "b6e07ad2e58207ec0d4d7d1008bbca11fe284bc2c1e77776bdfec0822d2f1724"
  end

  conflicts_with "terrabuild"
  conflicts_with "terrabuild-next"

  def install
    bin.install "terrabuild"
  end

  test do
    system "#{bin}/terrabuild version"
  end
end
