# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-tap
class TerrabuildNext < Formula
  desc "Seamless CI/CD tool for building and deploying monorepos."
  homepage "https://terrabuild.io"
  version "0.188.26-next"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.188.26-next/terrabuild-0.188.26-next-darwin-x64.zip"
    sha256 "1b8db08b01db911496a1c61160380c815f0b6fb4761e6706ea6587403e26ddb6"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.188.26-next/terrabuild-0.188.26-next-darwin-arm64.zip"
    sha256 "8f5156b85401a756a8430e62588b2ada7301900973996bd0eb5d1c7e5f898d26"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.188.26-next/terrabuild-0.188.26-next-linux-x64.zip"
    sha256 "f44ec07824c4150b565a79939410db94759872235127af3354eecdf0a45c2797"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.188.26-next/terrabuild-0.188.26-next-linux-arm64.zip"
    sha256 "8f2f978a4d616be6f81dc231439b6a7b9617e21b62da0dbd96baa9407c2fb9ea"
  end

  def install
    bin.install "terrabuild" => name
  end

  test do
    system bin/name, "version"
  end
end
