# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-tap
class TerrabuildBeta < Formula
  desc "Seamless CI/CD tool for building and deploying monorepos."
  homepage "https://terrabuild.io"
  version "0.135.6-beta"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.6-beta/terrabuild-0.135.6-beta-darwin-x64.zip"
    sha256 "bd6d770d0d67e16df6d3c5c80dfdb51cbe2881adfc7900d8e400c816334bb021"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.6-beta/terrabuild-0.135.6-beta-darwin-arm64.zip"
    sha256 "de80b6d3fef0aa039a8f9d358201ef92ff71c78e470aac8e774cf7b6236713be"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.6-beta/terrabuild-0.135.6-beta-linux-x64.zip"
    sha256 "28a02dd742163ca5483d5edb03225880694bc3a71ec09b3b8ff8d59d15248e4c"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.6-beta/terrabuild-0.135.6-beta-linux-arm64.zip"
    sha256 "8b8e129c4942a5df347b75a08efa05c5fde816f286981c77b20150aa4503f1df"
  end

  conflicts_with "terrabuild"
  conflicts_with "terrabuild-alpha"
  conflicts_with "terrabuild-beta"

  def install
    bin.install "terrabuild"
  end

  test do
    system "#{bin}/terrabuild version"
  end
end
