# This file was generated by https://github.com/magnusopera/terrabuild/blob/main/.github/scripts/generate-homebrew-tap
class TerrabuildBeta < Formula
  desc "Seamless CI/CD tool for building and deploying monorepos."
  homepage "https://terrabuild.io"
  version "0.135.17-beta"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.17-beta/terrabuild-0.135.17-beta-darwin-x64.zip"
    sha256 "4f4d1914616ce311b5ce0fd1b81dc82ab632c11acb593c56b78063cba26ecc5a"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.17-beta/terrabuild-0.135.17-beta-darwin-arm64.zip"
    sha256 "0807f7161ac0f11d4190d622271bdba7ea6fc41f72d3788aedb4111bd2e75526"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.17-beta/terrabuild-0.135.17-beta-linux-x64.zip"
    sha256 "fdac3ec1f5bef14c17850f3f177758bf0fa0938a7039a360fe66ac6780710f96"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/magnusopera/terrabuild/releases/download/0.135.17-beta/terrabuild-0.135.17-beta-linux-arm64.zip"
    sha256 "5e3b1ca8f99766ba44f81fc4bd753b0a7679574c33018f9edb2ff5da97520880"
  end

  conflicts_with "terrabuild"
  conflicts_with "terrabuild-alpha"
  conflicts_with "terrabuild-beta"

  def install
    bin.install "terrabuild"
  end

  test do
    system "#{bin}/terrabuild version"
  end
end
